### PR TITLE
Fix get description

### PR DESCRIPTION
**Pull request by psanford**
This pull request fixes getDescription when parseNamespace == false.

It is based on the work in pull #4. I can rebase it once #4 is merged if necessary.

### CODE REVIEW

**Comment by joshgummersall** [comment]
Nice work - thanks! I'm going to go ahead and merge this up.

**Comment by joshgummersall** [comment]
Actually - @psanford please do a quick rebase and then I will merge. Thanks!

**Comment by psanford** [comment]
Ok, I've rebased it.

**Comment by joshgummersall** [comment]
Just published https://www.npmjs.com/package/statsd-riemann-backend in v0.0.4

**Pull request merged**
